package org.fai.enums;

public enum PropertyEnums {

		URL,
		OVERRIDEREPORTS,
		PASSEDCASESSCREENSHOT,
		FAILEDCASESSCREENSHOT,
		SKIPPEDCASESSCREENSHOT,
		RETRYFAILEDCASES,
		BROWSER,
		EXTENTREPORTNAME,
		EXTENTREPORTTITILE,
		BROWSERMODE,
		USERNAME,
		PASSWORD,
		PROFILENAME,
		VALIDATORUSERNAME,
		VALIDATORPASSWORD,
		VALIDATORROLES,
		ADMINROLES
		
}
